name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          # - "macos-latest"
          # - "windows-latest"
        node_version:
          - "13"
          - "12"
          - "10"
          - "8"
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check package.json
        run: npm run sort-package-json

      - name: Run Tests
        run: npm run test-coverage

    release:
      name: Release
      runs-on: ubuntu-latest
      needs: [test]
      steps:
        - name: Checkout
          uses: actions/checkout@master
          with:
            depth: 1

        - name: Setup Node.js
          uses: actions/setup-node@master
          with:
            node-version: 12

        - name: Install Dependencies
          run: npm ci

        - name: Release
          run: npm run semantic-release
          env:
              # GH_TOKEN
            GITHUB_TOKEN: EyoxLB4ljxnY/8avLjT3cwMzxG0Tj10bbFfkM0me6LkWN44t7qm3fsyjAtxzPPizkFUozvMLIYdo2d6W4BpbL0f0y/wRBa/89pLrxXPFf/+d9N1QZh/8w8E+NsEc2MkiBMHh/08WDP8wBK/jwBmS1X6K9fVoPKUUu3egArb0mibPK+mkL0GpcLwtYajB3+5fwcdT5LkE/XcLiBXPiSviJHSsK/psG7tNnYvBH83rOcBEq4MP2vS/kEdMgnPpaM33uqjic3Pe/A7QHsveyTSwWjeDX//Upvc0T1Z+EoD0JrmtG1Mm4K1mnMqBz9I5AqZRERx8HcojERZ7zgIGIDUxaq7diSfepyjUknHsrpo0/lLR1N63oB3jpTphtUeAq6oGhguoOskbB9AvBMrV4AFmtOo+9gKe35UU/vTAN5OgmUAE0lD3GLGDcZyClmczXqM1/wxMDKQS911sDjPWx3R5anU0+E+UVAt/1Vlbdxo6isNPFBxYKHsk+jgCY+F+LmN5wJpqGmPGle/eopjqRvl9VUUgXPMP5/zZxbVCHJNNiFzhMwFhJTbTJzRELnv2gOwz7VhVDYdsJqB2xHOJCGX4j7os1r49Ul+bfcwnXWZY/CXCfcyJycC18OvaCjpttVOTJ6SHRONE6oFGT37nHuUexHWsOIKv/Y/yEBDGIXT84V8=
              # NPM_TOKEN 	7fc1
            NPM_TOKEN: JqPgVQiYdo8avWh72PVKDVKYOncgHJ8YHL2lSYiHCFWXk43SJhD+znbt63rZLQn7ePNKq6b9yL1ffuj+VkA4y79NGilLw9hQlZDMVI12+08+mm/PHCg79qEcu7Rg8lkbqsHtnjUDc3ssVefNMItjBxfiAWcoP4qke7wucBmaZT1fhzyl7CluwDrcgpCZG8VLCJ7YjQy59tzL/wWn8AfMIAQiWqhGDYf3BhAh2RKngQjblBJ5bn2hRq8KjELMbNz8/i6BIJV9v3xk4P9IHryQiFeJM0Unm0DxT9JNgKy9TWhyRmVpOPnPZTPQJBtZxmnGfxSVTAiS6SqrdZp2MUwG1W2I2rpgmKK6x4G+0SPOgRfRhjiSUh2w37HKELnSIhirmBRQlDHqbYKlTI75V57LMFcQSfUS4GubIqwlYkvsQuFX/ePQ6nFIp765PM4cz4ZnnzTohYcDJxpnrbEbnRBCCjKSXJmLQQ2D8n8erk/14pjWrnG9em9jvCm1oay9nOK+dPhYSHU8dB2jtBb+24YKBukaavTqsco3BczSZ62NHIPzwUzBhWaAwYfYE+P4n8m3G7s3vfBUmeG6Fxaqv92zOQfwk48rcr+V6JPbzY21yZ/BPIlGx29b8TO+0jMGZBZlu4dmsckYb6d1GB8b4fKN2ZFSyTuOZrb54B70ywlXh8Q=

