sudo: false
language: node_js
cache:
  directories:
    - /home/travis/.npm
node_js:
  - v8
  - v10
  - stable
script:
  - npm run sort-package-json
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
env:
  global:
      # GH_TOKEN
    - secure: EyoxLB4ljxnY/8avLjT3cwMzxG0Tj10bbFfkM0me6LkWN44t7qm3fsyjAtxzPPizkFUozvMLIYdo2d6W4BpbL0f0y/wRBa/89pLrxXPFf/+d9N1QZh/8w8E+NsEc2MkiBMHh/08WDP8wBK/jwBmS1X6K9fVoPKUUu3egArb0mibPK+mkL0GpcLwtYajB3+5fwcdT5LkE/XcLiBXPiSviJHSsK/psG7tNnYvBH83rOcBEq4MP2vS/kEdMgnPpaM33uqjic3Pe/A7QHsveyTSwWjeDX//Upvc0T1Z+EoD0JrmtG1Mm4K1mnMqBz9I5AqZRERx8HcojERZ7zgIGIDUxaq7diSfepyjUknHsrpo0/lLR1N63oB3jpTphtUeAq6oGhguoOskbB9AvBMrV4AFmtOo+9gKe35UU/vTAN5OgmUAE0lD3GLGDcZyClmczXqM1/wxMDKQS911sDjPWx3R5anU0+E+UVAt/1Vlbdxo6isNPFBxYKHsk+jgCY+F+LmN5wJpqGmPGle/eopjqRvl9VUUgXPMP5/zZxbVCHJNNiFzhMwFhJTbTJzRELnv2gOwz7VhVDYdsJqB2xHOJCGX4j7os1r49Ul+bfcwnXWZY/CXCfcyJycC18OvaCjpttVOTJ6SHRONE6oFGT37nHuUexHWsOIKv/Y/yEBDGIXT84V8=
      # NPM_TOKEN 	7fc1
    - secure: JqPgVQiYdo8avWh72PVKDVKYOncgHJ8YHL2lSYiHCFWXk43SJhD+znbt63rZLQn7ePNKq6b9yL1ffuj+VkA4y79NGilLw9hQlZDMVI12+08+mm/PHCg79qEcu7Rg8lkbqsHtnjUDc3ssVefNMItjBxfiAWcoP4qke7wucBmaZT1fhzyl7CluwDrcgpCZG8VLCJ7YjQy59tzL/wWn8AfMIAQiWqhGDYf3BhAh2RKngQjblBJ5bn2hRq8KjELMbNz8/i6BIJV9v3xk4P9IHryQiFeJM0Unm0DxT9JNgKy9TWhyRmVpOPnPZTPQJBtZxmnGfxSVTAiS6SqrdZp2MUwG1W2I2rpgmKK6x4G+0SPOgRfRhjiSUh2w37HKELnSIhirmBRQlDHqbYKlTI75V57LMFcQSfUS4GubIqwlYkvsQuFX/ePQ6nFIp765PM4cz4ZnnzTohYcDJxpnrbEbnRBCCjKSXJmLQQ2D8n8erk/14pjWrnG9em9jvCm1oay9nOK+dPhYSHU8dB2jtBb+24YKBukaavTqsco3BczSZ62NHIPzwUzBhWaAwYfYE+P4n8m3G7s3vfBUmeG6Fxaqv92zOQfwk48rcr+V6JPbzY21yZ/BPIlGx29b8TO+0jMGZBZlu4dmsckYb6d1GB8b4fKN2ZFSyTuOZrb54B70ywlXh8Q=
